---
  - name: Installing and Launch Filebeat
    hosts: webservers
    become: yes
    tasks:
      - name: Download .deb file
        command: curl -L -O https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.6.1-amd64.deb

      - name: Install .deb
        command: sudo dpkg -i filebeat-7.6.1-amd64.deb

      - name: Drop in filebeat.yml
        copy:
          src: /etc/ansible/files/filebeat-config.yml
          dest: /etc/filebeat/files/filebeat.yml

      - name: Enable and Configure System Module
        command: sudo filebeat modules enable system

      - name: Setup filebeat
        command: sudo filebeat setup

      - name: Start filebeat service
        command: sudo service filebeat start

      - name: Enable service filebeat on boot
        systemd:
          name: filebeat
          enabled: yes
